services:
  - type: web
    name: audio-transcriber
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: SARVAM_API_KEY
        value: YOUR_API_KEY_HERE
    build:
      pythonVersion: 3.10
